/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package test.java.CarFactoryPattern;

import static org.junit.Assert.assertTrue;

import main.java.CarFactoryPattern.Library;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
