/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package main.java.CarFactoryPattern;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
